// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://cufdemvvewfqkwrszotl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImN1ZmRlbXZ2ZXdmcWt3cnN6b3RsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk5OTM3NjEsImV4cCI6MjA2NTU2OTc2MX0.AWyyiiPCP8Y-RwnOvvVTw0kEbxdVsr8u_SH6TeF7m8I";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);